name: flutter_ion
version: 1.0.0
description: Ion SDK for flutter, For live broadcast, video conference, etc., support mobile/deskop/web.
homepage: https://github.com/pion/ion-sdk-flutter
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  events2: ^1.0.0
  flutter_webrtc: ^0.9.48+hotfix.1
  grpc: ^3.2.4
  protobuf: ^3.1.0
  sdp_transform: ^0.3.2
  uuid: ^4.3.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  test: ^1.25.2
